version: '3.9'

services:

  postgres_db:
    container_name: postgres_db
    image: postgres:16.3-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/
    restart: always
    shm_size: 128mb
    env_file:
      - ./dotenv_files/.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080